run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck      # エラーチェックの漏れを検出
    - gosimple      # コードの簡素化を提案
    - govet         # go vet による検査
    - ineffassign   # 無効な代入を検出
    - staticcheck   # 静的解析
    - unused        # 未使用のコードを検出
    - gofmt         # フォーマットチェック
    - goimports     # import の整理
    - misspell      # スペルミスを検出
    - revive        # golint の後継
    - gosec         # セキュリティ問題を検出
    - gocritic      # コードレビュー的な指摘
    - unparam       # 未使用のパラメータを検出
    - unconvert     # 不要な型変換を検出
    - dupl          # 重複コードを検出
    - prealloc      # スライスの事前割り当てを提案
    - exportloopref # ループ変数のポインタ参照問題を検出

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    check-shadowing: true
    enable-all: true

  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/shoppingjaws/tf-refactoring-block-uncommenter

  revive:
    confidence: 0.8
    rules:
      - name: exported
        disabled: false
      - name: package-comments
        disabled: false

  gosec:
    excludes:
      - G204  # コマンド実行（Git コマンドで必要）

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
    disabled-checks:
      - whyNoLint

  dupl:
    threshold: 100

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

  # 除外するパターン
  exclude-rules:
    # テストファイルでは一部のチェックを緩和
    - path: _test\.go
      linters:
        - errcheck
        - dupl
        - gosec
        - gocritic

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
